import { useEffect, useMemo, useRef, useState } from "react";
import { onAuthStateChanged, signInWithPopup, signOut } from "firebase/auth";
import {
  collection,
  doc,
  getDoc,
  getDocs,
  limit,
  onSnapshot,
  orderBy,
  query,
  setDoc,
  where,
} from "firebase/firestore";
import { auth, db, googleProvider } from "./firebase.js";
import MatchCard from "./components/MatchCard.jsx";
import Leaderboard from "./components/Leaderboard.jsx";
import MyPicks from "./components/MyPicks.jsx";
import Groups from "./components/Groups.jsx";
import Bracket from "./components/Bracket.jsx";

const TABS = [
  { id: "fixtures", label: "Fixtures" },
  { id: "picks", label: "My Picks" },
  { id: "bracket", label: "Bracket" },
  { id: "groups", label: "Leagues" },
  { id: "table", label: "Leaderboard" },
];

export default function App() {
  const [user, setUser] = useState(null);
  const [authReady, setAuthReady] = useState(false);
  const [tab, setTab] = useState("fixtures");
  const [matches, setMatches] = useState([]);
  const [predictions, setPredictions] = useState({}); // matchId -> prediction
  const [loadingMatches, setLoadingMatches] = useState(true);
  const [leaderTop, setLeaderTop] = useState(null); // { name, points }
  const [latestRoast, setLatestRoast] = useState(null); // { roastText, targetName, matchName, finalScore }

  // Auth state
  useEffect(() => {
    return onAuthStateChanged(auth, (u) => {
      setUser(u);
      setAuthReady(true);
    });
  }, []);

  // First-ever sign-in: create the user's Firestore doc with sane defaults
  // (auto-pick safety net ON) so brand-new players are covered immediately,
  // even if they never open My Picks. Existing users are left untouched.
  useEffect(() => {
    if (!user) return;
    let cancelled = false;
    (async () => {
      try {
        const ref = doc(db, "users", user.uid);
        const snap = await getDoc(ref);
        if (!cancelled && !snap.exists()) {
          await setDoc(ref, {
            displayName: user.displayName || "Anonymous",
            photoURL: user.photoURL || "",
            email: user.email || "",
            remindersOn: false,
            autoPickOn: true,
          });
        }
      } catch (e) {
        console.error("Could not initialize new user profile:", e);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [user]);

  // Top leaderboard player for hero roast card (live)
  useEffect(() => {
    const q = query(
      collection(db, "users"),
      orderBy("points", "desc"),
      limit(1)
    );
    return onSnapshot(q, (snap) => {
      if (snap.empty) {
        setLeaderTop(null);
        return;
      }
      const data = snap.docs[0].data();
      const pts = data.points || 0;
      setLeaderTop(
        pts > 0
          ? { name: data.nickname || data.displayName || "Anonymous", points: pts }
          : null
      );
    });
  }, []);

  // Most recent site-wide roast — the headline "win and get roasted" hook
  // on the homepage. Public read, no sign-in required (see globalRoasts
  // rule in firestore.rules); generated by scripts/syncMatches.js whenever
  // a match finishes.
  useEffect(() => {
    const q = query(
      collection(db, "globalRoasts"),
      orderBy("generatedAt", "desc"),
      limit(1)
    );
    return onSnapshot(
      q,
      (snap) => setLatestRoast(snap.empty ? null : snap.docs[0].data()),
      () => setLatestRoast(null)
    );
  }, []);

  // Matches (live)
  useEffect(() => {
    const q = query(collection(db, "matches"), orderBy("kickoff", "asc"));
    return onSnapshot(q, (snap) => {
      setMatches(snap.docs.map((d) => ({ id: d.id, ...d.data() })));
      setLoadingMatches(false);
    });
  }, []);

  // My predictions (live)
  useEffect(() => {
    if (!user) {
      setPredictions({});
      return;
    }
    const q = query(collection(db, "predictions"), where("uid", "==", user.uid));
    return onSnapshot(q, (snap) => {
      const map = {};
      snap.docs.forEach((d) => {
        map[d.data().matchId] = d.data();
      });
      setPredictions(map);
    });
  }, [user]);

  const myPoints = useMemo(() => {
    let pts = 0;
    matches.forEach((m) => {
      const p = predictions[m.id];
      if (!p || m.status !== "finished") return;
      if (p.home === m.homeScore && p.away === m.awayScore) pts += 5;
      else if (
        Math.sign(p.home - p.away) === Math.sign(m.homeScore - m.awayScore)
      )
        pts += 3;
    });
    return pts;
  }, [matches, predictions]);

  const upcoming = matches.filter((m) => m.status !== "finished");
  const finished = matches.filter((m) => m.status === "finished");

  async function handleSignIn() {
    try {
      await signInWithPopup(auth, googleProvider);
    } catch (e) {
      if (e.code !== "auth/popup-closed-by-user") {
        alert("Sign-in failed: " + e.message);
      }
    }
  }

  return (
    <div className="shell">
      <div className="pitch-lines" aria-hidden="true">
        <span className="halfway" />
        <span className="circle" />
      </div>

      <header className="topbar">
        <a className="wordmark" href="/">
          <span className="wordmark-badge" aria-hidden="true" />
          Football<span className="accent67">67</span>
          <small>Match Predictor</small>
        </a>

        {authReady &&
          (user ? (
            <div className="account">
              <span className="account-pts">
                <b>{myPoints}</b> pts
              </span>
              <AccountMenu user={user} />
              <button className="btn ghost" onClick={() => signOut(auth)}>
                Sign out
              </button>
            </div>
          ) : (
            <button className="btn solid" onClick={handleSignIn}>
              <GoogleMark /> Sign in with Google
            </button>
          ))}
      </header>

      <section className="hero">
        <p className="hero-eyebrow">Matchday is open</p>
        <h1>
          Call the score.
          <br />
          <em>Before the whistle.</em>
        </h1>
        <p className="hero-roast-tagline">Correct Result gets you Roasted! 🔥</p>
        <p className="hero-sub">
          Lock in a scoreline for every fixture before kickoff. Exact score
          pays <b>5&nbsp;pts</b>, the right result pays <b>3&nbsp;pts</b>.
          Get it right and the site roasts you for it.
        </p>
        {latestRoast ? (
          <div className="hero-roast-card hero-roast-card--live">
            <div className="hero-roast-header">
              <span className="hero-roast-flame">🔥</span>
              <span className="hero-roast-label">Just got roasted</span>
            </div>
            <div className="hero-roast-body">
              <div className="hero-roast-leader">
                <span className="hero-roast-name">{latestRoast.targetName}</span>
                {latestRoast.matchName && (
                  <span className="hero-roast-pts">
                    {latestRoast.matchName}
                    {latestRoast.finalScore ? ` · ${latestRoast.finalScore}` : ""}
                  </span>
                )}
              </div>
              <p className="hero-roast-quote">{latestRoast.roastText}</p>
              <p className="hero-roast-caption">
                Call it right and the whole site finds out.
              </p>
            </div>
          </div>
        ) : (
          leaderTop &&
          leaderTop.points > 0 && (
            <div className="hero-roast-card">
              <div className="hero-roast-header">
                <span className="hero-roast-flame">🔥</span>
                <span className="hero-roast-label">This week's target</span>
              </div>
              <div className="hero-roast-body">
                <div className="hero-roast-leader">
                  <span className="hero-roast-name">{leaderTop.name}</span>
                  <span className="hero-roast-pts">{leaderTop.points} pts</span>
                </div>
                <p className="hero-roast-quote">
                  Riding a hot streak or just vibing? Either way, they're going down.
                </p>
              </div>
            </div>
          )
        )}
        {!user && authReady && (
          <button className="btn solid lg" onClick={handleSignIn}>
            <GoogleMark /> Sign in to play
          </button>
        )}
      </section>

      <nav className="tabs" role="tablist">
        {TABS.map((t) => (
          <button
            key={t.id}
            role="tab"
            aria-selected={tab === t.id}
            className={tab === t.id ? "tab active" : "tab"}
            onClick={() => setTab(t.id)}
          >
            {t.label}
          </button>
        ))}
      </nav>

      <main>
        {tab === "fixtures" && (
          <>
            {loadingMatches && <p className="empty">Loading fixtures…</p>}
            {!loadingMatches && matches.length === 0 && (
              <p className="empty">
                No fixtures yet. Run <code>npm run seed</code> to add some.
              </p>
            )}

            {upcoming.length > 0 && (
              <h2 className="section-label">Upcoming</h2>
            )}
            {upcoming.map((m) => (
              <MatchCard
                key={m.id}
                match={m}
                user={user}
                prediction={predictions[m.id]}
                onRequireSignIn={handleSignIn}
              />
            ))}

            {finished.length > 0 && (
              <h2 className="section-label">Full time</h2>
            )}
            {finished.map((m) => (
              <MatchCard
                key={m.id}
                match={m}
                user={user}
                prediction={predictions[m.id]}
                onRequireSignIn={handleSignIn}
              />
            ))}
          </>
        )}

        {tab === "picks" && (
          <MyPicks
            user={user}
            matches={matches}
            predictions={predictions}
            onRequireSignIn={handleSignIn}
          />
        )}

        {tab === "bracket" && <Bracket user={user} onRequireSignIn={handleSignIn} />}

        {tab === "groups" && <Groups user={user} matches={matches} onRequireSignIn={handleSignIn} />}

        {tab === "table" && <Leaderboard me={user} />}
      </main>

      <footer className="foot">
        football67.com · results by football-data.org · Not affiliated with FIFA.
      </footer>
    </div>
  );
}

function GoogleMark() {
  return (
    <svg className="gmark" viewBox="0 0 24 24" width="16" height="16" aria-hidden="true">
      <path fill="#EA4335" d="M12 5.04c1.62 0 3.06.56 4.2 1.64l3.12-3.12C17.4 1.78 14.94.75 12 .75 7.55.75 3.7 3.3 1.82 7.02l3.66 2.84C6.36 7.1 8.94 5.04 12 5.04z"/>
      <path fill="#4285F4" d="M23.25 12.27c0-.93-.08-1.6-.26-2.3H12v4.35h6.44c-.13 1.08-.83 2.7-2.39 3.79l3.57 2.77c2.14-1.97 3.63-4.88 3.63-8.61z"/>
      <path fill="#FBBC05" d="M5.5 14.14a6.9 6.9 0 0 1-.37-2.14c0-.74.13-1.46.35-2.14L1.82 7.02A11.2 11.2 0 0 0 .75 12c0 1.8.43 3.5 1.07 4.98l3.68-2.84z"/>
      <path fill="#34A853" d="M12 23.25c3.04 0 5.6-1 7.46-2.72l-3.57-2.77c-.95.66-2.23 1.13-3.89 1.13-3.06 0-5.64-2.06-6.5-4.75l-3.68 2.84C3.7 20.7 7.55 23.25 12 23.25z"/>
    </svg>
  );
}

// Avatar button in the topbar that opens the profile/nickname dropdown.
function AccountMenu({ user }) {
  const [open, setOpen] = useState(false);
  const wrapRef = useRef(null);

  useEffect(() => {
    function handleOutside(e) {
      if (wrapRef.current && !wrapRef.current.contains(e.target)) setOpen(false);
    }
    document.addEventListener("mousedown", handleOutside);
    return () => document.removeEventListener("mousedown", handleOutside);
  }, []);

  return (
    <div className="account-menu" ref={wrapRef}>
      <button
        className="avatar-btn"
        onClick={() => setOpen((o) => !o)}
        aria-haspopup="true"
        aria-expanded={open}
        aria-label="Open profile menu"
      >
        {user.photoURL ? (
          <img className="avatar" src={user.photoURL} alt="" referrerPolicy="no-referrer" />
        ) : (
          <span className="avatar fallback" aria-hidden="true" />
        )}
      </button>
      {open && <ProfileDropdown user={user} onClose={() => setOpen(false)} />}
    </div>
  );
}

// Nickname editor — moved here from My Picks so it lives at the top of the
// page, next to Sign in / Sign out.
function ProfileDropdown({ user, onClose }) {
  const [saved, setSaved] = useState(undefined); // nickname currently in Firestore
  const [value, setValue] = useState("");
  const [busy, setBusy] = useState(false);
  const [flash, setFlash] = useState("");

  useEffect(
    () =>
      onSnapshot(doc(db, "users", user.uid), (s) => {
        const nick = s.exists() ? s.data().nickname || "" : "";
        setSaved(nick);
        setValue((v) => (v === "" || v === saved ? nick : v));
      }),
    [user.uid] // eslint-disable-line react-hooks/exhaustive-deps
  );

  if (saved === undefined) return null;

  const trimmed = value.trim();
  const valid = /^[A-Za-z0-9 _-]{3,20}$/.test(trimmed);
  const dirty = trimmed !== saved;

  async function save() {
    if (!valid || !dirty) return;
    setBusy(true);
    try {
      // Best-effort uniqueness check so two players don't share a name
      const clash = await getDocs(
        query(collection(db, "users"), where("nickname", "==", trimmed), limit(1))
      );
      if (!clash.empty && clash.docs[0].id !== user.uid) {
        setFlash("taken");
        setTimeout(() => setFlash(""), 2200);
        return;
      }
      await setDoc(
        doc(db, "users", user.uid),
        {
          displayName: user.displayName || "Anonymous",
          photoURL: user.photoURL || "",
          nickname: trimmed,
        },
        { merge: true }
      );
      setFlash("saved");
      setTimeout(() => setFlash(""), 1600);
    } catch (e) {
      alert("Could not save nickname: " + e.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="profile-dropdown" role="menu">
      <button className="profile-close" onClick={onClose} aria-label="Close profile menu">
        ×
      </button>
      <div className="profile-id">
        {user.photoURL ? (
          <img className="profile-avatar" src={user.photoURL} alt="" referrerPolicy="no-referrer" />
        ) : (
          <span className="profile-avatar fallback" aria-hidden="true" />
        )}
        <div>
          <p className="panel-eyebrow">Profile</p>
          <p className="profile-shown">{saved || user.displayName || "Anonymous"}</p>
          <p className="panel-note">
            {saved
              ? "Your nickname is what everyone sees on leaderboards and leagues."
              : "Set a nickname — it replaces your Google name on leaderboards and leagues."}
          </p>
        </div>
      </div>
      <div className="tb-input-row">
        <input
          className="tb-input wide"
          value={value}
          maxLength={20}
          placeholder="e.g. xGoalMachine"
          aria-label="Nickname"
          onChange={(e) => setValue(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && save()}
        />
        <button className="btn solid" onClick={save} disabled={busy || !valid || !dirty}>
          {busy
            ? "Checking…"
            : flash === "saved"
            ? "Saved ✓"
            : flash === "taken"
            ? "Name taken"
            : saved
            ? "Update"
            : "Save"}
        </button>
      </div>
      {trimmed !== "" && !valid && (
        <p className="profile-hint">3–20 characters: letters, numbers, spaces, - and _ only.</p>
      )}
    </div>
  );
}
